import { createPagesFunctionHandler } from "@react-router/cloudflare";
import { PrismaD1 } from '@prisma/adapter-d1';
import { PrismaClient } from '@prisma/client';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import * as build from "../build/server";

export const onRequest = createPagesFunctionHandler({
  build,
  getLoadContext: ({ context }) => {
    const adapter = new PrismaD1(context.cloudflare.env.DB);
    const prismaClient = new PrismaClient({ adapter });

    return {
      prismaClient,
    };
  }
});
