# workers_dev = true
name = "whist"
compatibility_date = "2024-12-23"
compatibility_flags = ["nodejs_compat"]
# assets = { directory = "./build/client/" }
pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "whist"
database_id = "c9cb65dc-b622-4a77-8cb4-e44aded533c7"